name: Barkeeper
author: caliog
website: http://www.caliog.org
main: org.caliog.Barkeeper.Barkeeper
version: 1.0.2

commands:
    barkeeper:
        usage: /barkeeper
        description: Shows information about the plugin!
    display:
        usage: /display <bottom|center|top> [time|speed] [world] <message> [sub-message]
        description: Display a message on the screen!